AWSTemplateFormatVersion: '2010-09-09'
Description: > 
  This Cloudformation Template deploys the network for the application infrastructure.
  Disclaimer: Not for production use. Demo and testing purposes only.

Parameters:
  BBBVPCCIDR:
    Description: IP range (CIDR notation) for the VPC
    Type: String
    Default: 10.1.0.0/16
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
  
  BBBNumberOfAZs:
    Description: Amount of Availability Zones to utilize
    Type: Number
    AllowedValues: [1, 2, 3]
    Default: 3
  
  BBBEnvironmentType:
    Description: 'Defines the environment type'
    AllowedValues: [scalable, single]
    Type: String
  
  BBBEnvironmentStage:
    Type: String
    Description: Select the appropriate environment
    AllowedValues: [stage, prod, dev]

Conditions: 
  BBBScalableEnvironment: !Equals [!Ref BBBEnvironmentType, scalable]
  BBBScalableandProdEnvironment: !And 
    - !Equals [!Ref BBBEnvironmentType, scalable]
    - !Equals [!Ref BBBEnvironmentStage, prod]
  BBBBuild2AZs: !Not [!Equals [!Ref BBBNumberOfAZs, 1]]
  BBBBuild3AZs: !Equals [!Ref BBBNumberOfAZs, 3]

Resources:
  BBBVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref BBBVPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true

  BBBIGW:
    Type: AWS::EC2::InternetGateway

  BBBIGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref BBBIGW
      VpcId: !Ref BBBVPC

  # Dynamic Public Application Subnets
  BBBPublicApplicationSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BBBVPC
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      CidrBlock: !Select [0, !Cidr [!Ref BBBVPCCIDR, 9, 8]]

  BBBPublicApplicationSubnet2:
    Type: AWS::EC2::Subnet
    Condition: BBBBuild2AZs
    Properties:
      VpcId: !Ref BBBVPC
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      CidrBlock: !Select [1, !Cidr [!Ref BBBVPCCIDR, 9, 8]]

  BBBPublicApplicationSubnet3:
    Type: AWS::EC2::Subnet
    Condition: BBBBuild3AZs
    Properties:
      VpcId: !Ref BBBVPC
      AvailabilityZone: !Select [2, !GetAZs '']
      MapPublicIpOnLaunch: true
      CidrBlock: !Select [2, !Cidr [!Ref BBBVPCCIDR, 9, 8]]

  # Dynamic Private Application Subnets
  BBBPrivateApplicationSubnet1:
    Type: AWS::EC2::Subnet
    Condition: BBBScalableEnvironment
    Properties:
      VpcId: !Ref BBBVPC
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false
      CidrBlock: !Select [3, !Cidr [!Ref BBBVPCCIDR, 9, 8]]

  BBBPrivateApplicationSubnet2:
    Type: AWS::EC2::Subnet
    Condition: BBBBuild2AZs
    Properties:
      VpcId: !Ref BBBVPC
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: false
      CidrBlock: !Select [4, !Cidr [!Ref BBBVPCCIDR, 9, 8]]

  BBBPrivateApplicationSubnet3:
    Type: AWS::EC2::Subnet
    Condition: BBBBuild3AZs
    Properties:
      VpcId: !Ref BBBVPC
      AvailabilityZone: !Select [2, !GetAZs '']
      MapPublicIpOnLaunch: false
      CidrBlock: !Select [5, !Cidr [!Ref BBBVPCCIDR, 9, 8]]

  # Dynamic Private DB Subnets
  BBBPrivateDBSubnet1:
    Type: AWS::EC2::Subnet
    Condition: BBBScalableEnvironment
    Properties:
      VpcId: !Ref BBBVPC
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false
      CidrBlock: !Select [6, !Cidr [!Ref BBBVPCCIDR, 9, 8]]

  BBBPrivateDBSubnet2:
    Type: AWS::EC2::Subnet
    Condition: BBBBuild2AZs
    Properties:
      VpcId: !Ref BBBVPC
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: false
      CidrBlock: !Select [7, !Cidr [!Ref BBBVPCCIDR, 9, 8]]

  BBBPrivateDBSubnet3:
    Type: AWS::EC2::Subnet
    Condition: BBBBuild3AZs
    Properties:
      VpcId: !Ref BBBVPC
      AvailabilityZone: !Select [2, !GetAZs '']
      MapPublicIpOnLaunch: false
      CidrBlock: !Select [8, !Cidr [!Ref BBBVPCCIDR, 9, 8]]

  # NAT Gateway Resources
  BBBNatGateway1EIP:
    Type: AWS::EC2::EIP
    Condition: BBBScalableEnvironment
    DependsOn: BBBIGWAttachment
    Properties:
      Domain: vpc

  BBBNatGateway2EIP:
    Type: AWS::EC2::EIP
    Condition: BBBScalableandProdEnvironment
    DependsOn: BBBIGWAttachment
    Properties:
      Domain: vpc

  BBBNatGateway1:
    Type: AWS::EC2::NatGateway
    Condition: BBBScalableEnvironment
    Properties:
      AllocationId: !GetAtt BBBNatGateway1EIP.AllocationId
      SubnetId: !Ref BBBPublicApplicationSubnet1

  BBBNatGateway2:
    Type: AWS::EC2::NatGateway
    Condition: BBBScalableandProdEnvironment
    Properties:
      AllocationId: !GetAtt BBBNatGateway2EIP.AllocationId
      SubnetId: !Ref BBBPublicApplicationSubnet2

  # Route Tables
  BBBPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BBBVPC

  BBBDefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: BBBIGWAttachment
    Properties:
      RouteTableId: !Ref BBBPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref BBBIGW

  BBBPublicApplicationSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref BBBPublicRouteTable
      SubnetId: !Ref BBBPublicApplicationSubnet1

  BBBPublicApplicationSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: BBBBuild2AZs
    Properties:
      RouteTableId: !Ref BBBPublicRouteTable
      SubnetId: !Ref BBBPublicApplicationSubnet2

  BBBPublicApplicationSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: BBBBuild3AZs
    Properties:
      RouteTableId: !Ref BBBPublicRouteTable
      SubnetId: !Ref BBBPublicApplicationSubnet3

  BBBPrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Condition: BBBScalableEnvironment
    Properties:
      VpcId: !Ref BBBVPC

  BBBDefaultPrivateRoute1:
    Type: AWS::EC2::Route
    Condition: BBBScalableEnvironment
    Properties:
      RouteTableId: !Ref BBBPrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref BBBNatGateway1

  BBBPrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Condition: BBBBuild2AZs
    Properties:
      VpcId: !Ref BBBVPC

  BBBDefaultPrivateRoute2:
    Type: AWS::EC2::Route
    Condition: BBBScalableandProdEnvironment
    Properties:
      RouteTableId: !Ref BBBPrivateRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref BBBNatGateway2

Outputs:
  BBBVPC:
    Description: VPC ID
    Value: !Ref BBBVPC

  BBBPublicApplicationSubnets:
    Description: A list of the public Application subnets
    Value: !Join [ ",", [ !Ref BBBPublicApplicationSubnet1, !If [ BBBBuild2AZs, !Ref BBBPublicApplicationSubnet2,  !Ref "AWS::NoValue"], !If [ BBBBuild3AZs, !Ref BBBPublicApplicationSubnet3,  !Ref "AWS::NoValue"]]]

  BBBPrivateApplicationSubnets:
    Description: A list of the private Instance subnets
    Condition: BBBScalableEnvironment
    Value: !Join [ ",", [ !Ref BBBPrivateApplicationSubnet1, !If [ BBBBuild2AZs, !Ref BBBPrivateApplicationSubnet2,  !Ref "AWS::NoValue"], !If [ BBBBuild3AZs, !Ref BBBPrivateApplicationSubnet3,  !Ref "AWS::NoValue"]]]

  BBBPrivateDBSubnets:
    Description: A list of the private database subnets
    Condition: BBBScalableEnvironment
    Value: !Join [ ",", [ !Ref BBBPrivateDBSubnet1, !If [ BBBBuild2AZs, !Ref BBBPrivateDBSubnet2,  !Ref "AWS::NoValue"], !If [ BBBBuild3AZs, !Ref BBBPrivateDBSubnet3,  !Ref "AWS::NoValue"]]]