AWSTemplateFormatVersion: '2010-09-09'
Description: > 
  This Cloudformation Template deploys the network for the application infrastructure.
  Disclaimer: Not for production use. Demo and testing purposes only.

Parameters:
  BBBVPCDEF:
    Description: IP range (CIDR notation) for the VPC
    Type: String
    Default: 10.1.0.0/16
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
  
  BBBNumberOfAZs:
    Description: Amount of Availability Zones to utilize
    Type: Number
    AllowedValues: [1, 2, 3]
    Default: 3
  
  BBBEnvironmentType:
    Description: 'Defines the environment type'
    AllowedValues: [scalable, single]
    Type: String
  
  BBBEnvironmentStage:
    Type: String
    Description: Select the appropriate environment
    AllowedValues: [stage, prod, dev]

Conditions: 
  BBBScalableEnvironment: !Equals [!Ref BBBEnvironmentType, scalable]
  BBBScalableandProdEnvironment: !And 
    - !Equals [!Ref BBBEnvironmentType, scalable]
    - !Equals [!Ref BBBEnvironmentStage, prod]
  BBBBuild2AZs: !Not [!Equals [!Ref BBBNumberOfAZs, 1]]
  BBBBuild3AZs: !Equals [!Ref BBBNumberOfAZs, 3]

Resources:
  BBBVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref BBBVPCDEF
      EnableDnsSupport: true
      EnableDnsHostnames: true

  BBBIGW:
    Type: AWS::EC2::InternetGateway

  BBBIGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref BBBIGW
      VpcId: !Ref BBBVPC

  # Dynamic Application Subnets
  BBBApplicationSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BBBVPC
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      CidrBlock: !Select [0, !Cidr [!Ref BBBVPCDEF, 9, 8]]

  BBBApplicationSubnet2:
    Type: AWS::EC2::Subnet
    Condition: BBBBuild2AZs
    Properties:
      VpcId: !Ref BBBVPC
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      CidrBlock: !Select [1, !Cidr [!Ref BBBVPCDEF, 9, 8]]

  BBBApplicationSubnet3:
    Type: AWS::EC2::Subnet
    Condition: BBBBuild3AZs
    Properties:
      VpcId: !Ref BBBVPC
      AvailabilityZone: !Select [2, !GetAZs '']
      MapPublicIpOnLaunch: true
      CidrBlock: !Select [2, !Cidr [!Ref BBBVPCDEF, 9, 8]]

  # Dynamic Private Datastore Subnets
  BBBDatastoreSubnet1:
    Type: AWS::EC2::Subnet
    Condition: BBBScalableEnvironment
    Properties:
      VpcId: !Ref BBBVPC
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false
      CidrBlock: !Select [6, !Cidr [!Ref BBBVPCDEF, 9, 8]]

  BBBDatastoreSubnet2:
    Type: AWS::EC2::Subnet
    Condition: BBBBuild2AZs
    Properties:
      VpcId: !Ref BBBVPC
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: false
      CidrBlock: !Select [7, !Cidr [!Ref BBBVPCDEF, 9, 8]]

  BBBDatastoreSubnet3:
    Type: AWS::EC2::Subnet
    Condition: BBBBuild3AZs
    Properties:
      VpcId: !Ref BBBVPC
      AvailabilityZone: !Select [2, !GetAZs '']
      MapPublicIpOnLaunch: false
      CidrBlock: !Select [8, !Cidr [!Ref BBBVPCDEF, 9, 8]]

  # Route Tables
  BBBRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BBBVPC

  BBBDefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: BBBIGWAttachment
    Properties:
      RouteTableId: !Ref BBBRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref BBBIGW

  BBBApplicationSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref BBBRouteTable
      SubnetId: !Ref BBBApplicationSubnet1

  BBBApplicationSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: BBBBuild2AZs
    Properties:
      RouteTableId: !Ref BBBRouteTable
      SubnetId: !Ref BBBApplicationSubnet2

  BBBApplicationSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: BBBBuild3AZs
    Properties:
      RouteTableId: !Ref BBBRouteTable
      SubnetId: !Ref BBBApplicationSubnet3

Outputs:
  BBBVPC:
    Description: VPC ID
    Value: !Ref BBBVPC

  BBBApplicationSubnets:
    Description: A list of the application subnets
    Value: !Join [ ",", [ !Ref BBBApplicationSubnet1, !If [ BBBBuild2AZs, !Ref BBBApplicationSubnet2,  !Ref "AWS::NoValue"], !If [ BBBBuild3AZs, !Ref BBBApplicationSubnet3,  !Ref "AWS::NoValue"]]]

  BBBDatastoreSubnets:
    Description: A list of the database subnets
    Condition: BBBScalableEnvironment
    Value: !Join [ ",", [ !Ref BBBDatastoreSubnet1, !If [ BBBBuild2AZs, !Ref BBBDatastoreSubnet2,  !Ref "AWS::NoValue"], !If [ BBBBuild3AZs, !Ref BBBDatastoreSubnet3,  !Ref "AWS::NoValue"]]]