AWSTemplateFormatVersion: '2010-09-09'
Description: 'Redis Cluster (Amazon ElastiCache) template'

Parameters:
  BBBNotificationTopic:
    Description: Topic to be used for alarm notifications
    Type: String

  BBBCACHEDBInstanceType:
    Description: Instance type for Amazon ElastiCache (Redis)
    Type: String
    Default: cache.t3.micro

  BBBPrivateDBSubnets:
    Description: Comma separated list of the private database subnets
    Type: CommaDelimitedList
  
  BBBCACHEDBSecurityGroup:
    Description: Security Group that should be assigned for cache database
    Type: String

  BBBCacheAZMode:
    Description: Redis Cache AZ Mode
    Type: String
    Default: single-az
    AllowedValues:
      - single-az
      - cross-az

Mappings:
  CacheSettings:
    Redis:
      Engine: valkey
      Version: '7.2'
      Port: 6379
      Family: valkey7

Resources:
  BBBCacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: !Sub CacheSubnetGroup-${AWS::StackName}
      SubnetIds: !Ref BBBPrivateDBSubnets

  BBBParametersGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      CacheParameterGroupFamily: !FindInMap [CacheSettings, Redis, Family]
      Description: "Redis parameter group with performance optimizations"
      Properties:
        tcp-keepalive: 60
        timeout: 900

  BBBElasticacheRedis:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupId: !Sub ${AWS::StackName}-cache
      ReplicationGroupDescription: !Sub ${AWS::StackName} Cache Cluster
      NumCacheClusters: 1
      CacheNodeType: !Ref BBBCACHEDBInstanceType
      CacheParameterGroupName: !Ref BBBParametersGroup
      CacheSubnetGroupName: !Ref BBBCacheSubnetGroup
      Engine: !FindInMap [CacheSettings, Redis, Engine]
      EngineVersion: !FindInMap [CacheSettings, Redis, Version]
      Port: !FindInMap [CacheSettings, Redis, Port]
      NotificationTopicArn: !Ref BBBNotificationTopic
      SecurityGroupIds: [!Ref BBBCACHEDBSecurityGroup]
      AutomaticFailoverEnabled: false
      MultiAZEnabled: !Equals [!Ref BBBCacheAZMode, "cross-az"]

Outputs:
  BBBCacheDBAddress:
    Description: The Big Blue Button Cache Database Address
    Value: !GetAtt BBBElasticacheRedis.PrimaryEndPoint.Address

  BBBCacheDBPort:
    Description: The Big Blue Button Cache Database Port
    Value: !GetAtt BBBElasticacheRedis.PrimaryEndPoint.Port

  BBBElasticacheRedis:
    Description: The Big Blue Button Cache Redis Cluster
    Value: !Ref BBBElasticacheRedis

  BBBParametersGroup:
    Description: The Big Blue Button Cache Redis Parameter Group
    Value: !Ref BBBParametersGroup

  BBBCacheSubnetGroup:
    Description: The Big Blue Button Cache Redis Subnet Group
    Value: !Ref BBBCacheSubnetGroup
